# Generated by Django 5.2.8 on 2025-11-13 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRecused',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=40, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts_recused', to='expenses.expenses')),
            ],
            options={
                'verbose_name': 'Alerta de Recusa',
                'verbose_name_plural': 'Alerta de Recusa',
            },
        ),
    ]
