# Generated by Django 5.2.8 on 2025-11-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alertrecused'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertrecused',
            options={'verbose_name': 'Alerta de Recusa', 'verbose_name_plural': 'Alertas de Recusa'},
        ),
    ]
