# Generated by Django 5.2.8 on 2025-11-09 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_state_expenses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='amount',
            field=models.FloatField(blank=True, help_text='Adicione a quantidade aqui', null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='description',
            field=models.TextField(blank=True, help_text='Escreva a descriminação da despesa'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='nf',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='expenses',
            name='owner_expenses',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='expenses',
            name='picture',
            field=models.ImageField(blank=True, help_text='Adicione a imagem da nota fiscal', upload_to='pictures/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='state_uf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='expenses.state'),
        ),
        migrations.AddField(
            model_name='expenses',
            name='value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Digite o valor total da despesa', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='supply',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
