# Generated by Django 5.2.8 on 2025-11-13 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_userprofile_acount_userprofile_agency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='acount',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
