# Generated by Django 5.2.8 on 2025-11-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='nf',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
