# Generated by Django 5.2.8 on 2025-11-14 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_cycle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CURRENT', 'Conta corrente'), ('SAVINGS', 'Conta poupança'), ('SALARY', 'Conta salário')], default='-', max_length=15, null=True),
        ),
    ]
