# Generated by Django 5.2.8 on 2025-11-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0007_userprofile_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(blank=True, choices=[('Conta corrente', 'Conta corrente'), ('Conta poupança', 'Conta poupança'), ('Conta salário', 'Conta salário')], default='', max_length=15, null=True),
        ),
    ]
