# Generated by Django 5.2.8 on 2025-11-14 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_alter_userprofile_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='cost_center',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
