# Generated by Django 5.2.8 on 2025-11-15 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_userprofile_cost_center'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateCycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('initial_date', models.DateField()),
                ('end_date', models.DateField()),
                ('initial_km', models.IntegerField(blank=True, null=True)),
                ('end_km', models.IntegerField(blank=True, null=True)),
                ('is_open', models.BooleanField(default=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cycles_owner', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ciclo',
            },
        ),
        migrations.AlterField(
            model_name='expenses',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='expenses.createcycle'),
        ),
        migrations.DeleteModel(
            name='Cycle',
        ),
    ]
