# Generated by Django 5.2.8 on 2025-11-15 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0011_cycle_alter_expenses_cycle_delete_createcycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='cycle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='expenses.cycle'),
        ),
    ]
