# Generated by Django 5.2.8 on 2025-11-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_alter_expenses_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cycle',
            name='save_expense_auto',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
