# Generated by Django 5.2.8 on 2025-11-20 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0016_role_delete_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='cost_center',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
