# Generated by Django 5.2.8 on 2025-11-20 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0017_team_cost_center'),
    ]

    operations = [
    ]
