# Generated by Django 5.2.8 on 2025-11-20 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0019_userprofile_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='cost_center',
        ),
    ]
