# Generated by Django 5.2.8 on 2025-11-24 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0023_teaminvite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teaminvite',
            options={'verbose_name': 'Team Invite', 'verbose_name_plural': 'Team Invites'},
        ),
    ]
