# Generated by Django 5.2.8 on 2025-12-05 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0025_alter_cycle_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='teaminvite',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expenses.role'),
        ),
    ]
