# Generated by Django 5.2.8 on 2025-12-16 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0026_teaminvite_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='expenses.enterprise'),
        ),
    ]
