# Generated by Django 5.2.8 on 2025-12-16 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0027_userprofile_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenses',
            name='enterprise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses', to='expenses.enterprise'),
        ),
    ]
