# Generated by Django 5.2.8 on 2025-12-19 15:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0029_expenses_created_at_expenses_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Criada'), ('UPDATED', 'Atualizada'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Recusada'), ('STATUS_CHANGED', 'Status alterado'), ('DELETED', 'Excluída')], max_length=20)),
                ('ip_adress', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='expenses.expenses')),
                ('notes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_audits', to='expenses.alertrecused')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_audits', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_audits', to='expenses.status')),
            ],
            options={
                'verbose_name': 'Auditoria de despesa',
                'verbose_name_plural': 'Auditorias de Despesas',
                'indexes': [models.Index(fields=['expense', '-created_at'], name='expenses_ex_expense_3833c3_idx'), models.Index(fields=['performed_by', '-created_at'], name='expenses_ex_perform_34d808_idx')],
            },
        ),
    ]
