# Generated by Django 5.2.8 on 2025-12-19 15:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0030_expenseaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseaudit',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='expenses.expenses'),
        ),
    ]
