# Generated by Django 5.2.8 on 2025-12-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0031_alter_expenseaudit_expense'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseaudit',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Criação'), ('UPDATED', 'Atualização'), ('APPROVED', 'Aprovação'), ('REJECTED', 'Recusa'), ('DELETED', 'Exclusão')], max_length=20),
        ),
    ]
