# Generated by Django 5.2.8 on 2025-12-19 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0032_alter_expenseaudit_action'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expenseaudit',
            name='ip_adress',
        ),
        migrations.RemoveField(
            model_name='expenseaudit',
            name='user_agent',
        ),
    ]
