# Generated by Django 5.2.8 on 2025-12-19 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0033_remove_expenseaudit_ip_adress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expenses_status', to='expenses.status'),
        ),
    ]
