# Generated by Django 5.2.8 on 2025-12-19 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0034_alter_expenses_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseaudit',
            name='is_checked',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='expenses',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense', to='expenses.status'),
        ),
    ]
