# Generated by Django 5.2.8 on 2025-12-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0035_expenseaudit_is_checked_alter_expenses_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseaudit',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Criada'), ('UPDATED', 'Atualizada'), ('APPROVED', 'Aprovada'), ('REJECTED', 'Recusada'), ('DELETED', 'Excluída')], max_length=20),
        ),
    ]
